// This is a minimal service worker
// The actual service worker will be generated by @vite-pwa/sveltekit

// Install event handler
self.addEventListener('install', () => {
  self.skipWaiting();
});

// Activate event handler
self.addEventListener('activate', () => {
  self.clients.claim();
});
